title: Event-guided Foley Sound Synthesis Demo
description: Event-guided_FSS_Demo
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://github.com/tuur29/pages-themes-cayman
  zip_title: View Documentation
  zip_hide: false
  tar_hide: true
  github_hide: true